fix: extend HcalEndcapN r segments to rmin/rmax (#232)
### Briefly, what does this PR introduce?
We are encountering issues with tracks that return numerous warnings
like this:
```console
ERROR: Hit Position (1.32962276827011169900e+01) is below the acceptance (1.99431000000000011596e+01) of the segmentation
Position: Pre (                       (8.35509855972314454675e+01,-1.03429629682137914415e+02,-3.34259732049230251505e+03)) Post (                       (8.35453556905108314368e+01,-1.03439123309562916120e+02,-3.34259315786786373792e+03)) 
Momentum:  Pre (                       (-9.01134991035029281337e-02,-1.52323523319139481069e-01,6.67403254221919650657e-02))  Post (                       (-0.00000000000000000000e+00,-0.00000000000000000000e+00,0.00000000000000000000e+00)) 
```
These positions are in the HcalEndcapN. This extends the r segmentation
to the rmin and rmax.

### What kind of change does this PR introduce?
- [X] Bug fix (issue: segmentation issues in HcalEndcapN)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [X] Changes have been communicated to collaborators @lkosarz 

### Does this PR introduce breaking changes? What changes might users
need to make to their code?
No.

### Does this PR change default behavior?
No.