FileLoaderHelper: avoid supplying non-existent paths for fs::equivalent (#753)
### Briefly, what does this PR introduce?

This avoids triggering an exception every time path is updated:

```
cppyy.gbl.std.runtime_error: void dd4hep::sim::Geant4Kernel::loadGeometry(const string& compact_file) =>
    runtime_error: filesystem error: in equivalent: Operation not supported ["calibrations/pfrich.lut"] ["calibrations/17a7536e11d8bc3f"]
```


### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users
need to make to their code?
No

### Does this PR change default behavior?
No