MPGDDIRC: fix compilation error and some format strings (#209)
### Briefly, what does this PR introduce?
Fix compilation errors:
```output
src/MPGDDIRC_geo.cpp:126:52: error: cannot pass object of non-trivial type 'std::__1::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
        printout(DEBUG, "MPGDDIRC_geo", "gas: %f", comp_name);
                                                   ^
```

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users
need to make to their code?
No.

### Does this PR change default behavior?
No.