fix(dRICH): initialize `irt` object pointers (#101)
### Briefly, what does this PR introduce?
Fixes new build errors such as
```
error: ‘irtDetector’ may be used uninitialized
```

This issue only impacts builds with `cmake` option `-DIRT_AUXFILE=ON` (which will be removed soon in #6 anyway)

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [x] Tests for the changes have been added
- [x] Documentation has been added / updated
- [x] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
no

### Does this PR change default behavior?
no